title: 'Floripa Bitdevs'
tagline: 'BitDevs é uma comunidade para aqueles interessados em discutir e participar da pesquisa e desenvolvimento do Bitcoin e protocolos relacionados.'

menu:
  - {name: 'Sobre', url: '/about'}
  - {name: 'Eventos', url: '/events'}
  - {name: 'Meetup', url: 'meetup.com/pt-BR/floripa-bitdevs', external: true}
