title: 'Floripa BitTalks'
tagline: 'Floripa BitTalks é uma comunidade para aqueles interessados em discutir sobre Bitcoin e protocolos relacionados.'

menu:
  - {name: 'Sobre', url: '/about'}
  - {name: 'Encontros', url: '/events'}
  - {name: 'Meetup', url: 'https://meetup.com/pt-BR/floripa-bittalks', external: true}
